title: SFSU Cyber Security Club
description: Welcome to the matrix Neo
show_downloads: false
google_analytics: false
theme: jekyll-theme-hacker
url: sfsucybersecurity.club
# for resources collection
collections:
  blogs:
    output: true
  resources:
    output: true
